### ISSUE TITLE
Replay of multiple log files does not work anymore

### ISSUE THREAD

**Issue by mstoelzle** [rock-core/tools-pocolog#24]
It used to be possible to use pocolog to replay multiple log files at once by using the following format:
```
Orocos::Log::Replay.open(path_to_first_log, path_to_second_log, path_to_third_log)
```
This is known to work in for example commit `e31eb91ff4370fb413c03d38d58c2825ad4c3905` (https://github.com/rock-core/tools-pocolog/commit/e31eb91ff4370fb413c03d38d58c2825ad4c3905)

However, in the current master branch, this code fails with the following error:
```
/home/user/rock/tools/pocolog/lib/io_sequence.rb:27:in 'add_io': undefined method 'size' for nil:NilClass (NoMethodError)
```
![photo_2021-01-09 10 51 29](https://user-images.githubusercontent.com/2360366/104088675-dfd09f80-5268-11eb-8889-1cc306f2e2e6.jpeg)

**Comment by doudou** [comment]
Hi @mstoelzle. Please have a look at https://github.com/rock-core/tools-orocosrb/pull/139

**Comment by mstoelzle** [comment]
@doudou Thanks a lot. I just tried out the fix. It seems to be working - great!
