### ISSUE TITLE
`API documentation`'s link is broken

### ISSUE THREAD

**Issue by caioaamaral** [rock-core/tools-pocolog#28]
Seems like this project does not exist on RubyDoc.info
![image](https://user-images.githubusercontent.com/39931071/165526951-0c31d9df-0649-48e7-a3c5-ca83df02e741.png)

**Comment by varun19299** [comment]
Clicking Go doesn't seem to work for me.

**Comment by doudou** [comment]
Becomes available after a while ... not ideal. https://www.rubydoc.info/github/rock-core/tools-pocolog
